#!/usr/bin/env zsh
set -euo pipefail

BROWSER="qutebrowser"

SEARCHENGINE="
DEFAULT https://google.com/search?q={}\n
anime47 https://anime47.com/tim-nang-cao/?keyword={}\n
animehay https://animehay.tv/tim-kiem?q={}\n
sukidesuost https://sukidesuost.info/?s={}\n
shopee https://shopee.vn/search?keyword={}\n
am https://www.amazon.com/s?k={}\n
aw https://wiki.archlinux.org/?search={}\n
goog https://www.google.com/search?q={}\n
hoog https://hoogle.haskell.org/?hoogle={}\n
re https://www.reddit.com/r/{}\n
ub https://www.urbandictionary.com/define.php?term={}\n
wiki https://en.wikipedia.org/wiki/{}\n
yt https://www.youtube.com/results?search_query={}\n
"

QUICKMARK="
face facebook.com
yt youtube.com
grade gradescope.com
spire spire.umass.edu
mood moodle.umass.edu
fsm http://madebyevan.com/fsm/
RREF https://www.emathhelp.net/calculators/linear-algebra/reduced-row-echelon-form-rref-caclulator/?i=%5B%5B0%2Cx%2Cy%5D%2C%5B-x%2C0%2Cz%5D%2C%5B-y%2C-z%2C0%5D%5D&reduced=on
eigen https://matrixcalc.org/en/vectors.html
u4 https://www.youtube.com/
matrix https://matrixcalc.org/en/
duo https://duo.google.com/
cartoon https://wcostream.com
acs https://www.google.com/search?q=evil%20everywhere
maps https://www.google.com/maps
peterpan https://peterpanbus.com/
drive https://drive.google.com/drive/u/0/
am https://www.amazon.com/
cigars https://www.coronacigar.com/product/Cigars/Cigar-Boxes/Rocky-Patel-Vintage-1999-Robusto-Tubes-Cigars-RPVC10RT/
required https://1lib.us/book/539873/5d1785
moonami https://umass.moonami.com/
cs311 https://people.cs.umass.edu/~sheldon/teaching/cs311/
raw https://www.google.com/search?q=raw%20french%20movie
ebay https://www.ebay.com/
heroku https://signup.heroku.com/
teaching https://people.cs.umass.edu/~sheldon/teaching/cs311/
"


search(){
SEARCH=$(rofi -dmenu -p "Search");
if [ $(echo "$SEARCH" | wc -w) = 0 ];
then
elif [ $(echo "$SEARCH" | wc -w) = 1 ];
then
    if echo "$QUICKMARK" | awk '{print $1}' | grep "$SEARCH";
    then
	URL=$(echo "$QUICKMARK" | grep -Po "$SEARCH \K.*");
	$BROWSER $URL;
    else
	ENGINE=$(echo "$SEARCHENGINE" | grep -Po "DEFAULT \K.*")
	$BROWSER $ENGINE$SEARCH;
    fi
else
    POSSIBLEENGINE=$(echo "$SEARCH" | awk '{print $1}')
    if echo "$SEARCHENGINE" | awk '{print $1}' | grep "$POSSIBLEENGINE";
    then
	ENGINE=$(echo "$SEARCHENGINE" | grep "^$POSSIBLEENGINE" | grep -Po "^.* \K.*")
	SEARCH=$(echo "$SEARCH" | cut -d " " -f 2-)
	URL=$(echo $ENGINE | sed "s/{}/$SEARCH/g")
	$BROWSER $URL;
    else
	$BROWER $SEARCH
    fi
    
fi
}

case $1 in
search)
	search;
	;;
addquickmark)

	;;
addSearch)
	;;
*)
esac
