#!/usr/bin/env zsh
set -euo pipefail

function crop () {
    scrot -sf ${name};
    xclip -selection clipboard -t image/png ${name};
}

function window () {
    scrot -uf ${name};
    xclip -selection clipboard -t image/png ${name};
}

function all () {
    scrot -f  ${name};
    xclip -selection clipboard -t image/png ${name};
}

name=~/Pictures/Screenshots/$(date '+%m-%d-%Y_%H-%M-%S').png;
case "$1" in
    -c)
	crop 
	;;
    -w)
	window 
	;;
    -a)
    all
esac
